apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-docker-secret
  namespace: {{ .Values.autoscaling.namespace }}
type: "kubernetes.io/dockerconfigjson" 
data:
  .dockerconfigjson: <value>